# This is a TOML document.

#config = [ "./examples.d/simple.conf", "/tmp/toto.conf" ]

#host = "127.0.0.1:1234"

#data = "/tmp/bitfan"

# debug = true

verbose = true

# log = "/tmp/bitfan.log"

[plugin]
workers = 2

[webhook]
listen = "127.0.0.1:3333"

[prometheus]
listen = "127.0.0.1:1421"
path ="/metrics"

# [[log]]
# type = "file"
# path = "/tmp/bitfan.log"
