# This is a TOML document.

#config = [ "./examples.d/simple.conf", "/tmp/toto.conf" ]

#host = "127.0.0.1:3456"

data = "/tmp/logfan"

debug = true

verbose = true

log = "/tmp/logfan.log"

[plugin]
workers = 2

[webhook]
listen = "127.0.0.1:3333"

# [prometheus]
# listen = "127.0.0.1:24232"
# path ="/metrics"

# [[log]]
# type = "file"
# path = "/tmp/logfan.log"
